var 
DEBUG        = false,
webserver    = "localhost:8080",
websocket    = null,
height      = 8,
width      = 1,
framerate    = 1,
connecting   = false,
connected    = false,
timeout      = 1,
colors       = new Uint8Array(height*width*3),
canvas       = document.getElementById('matrix'),
context      = canvas.getContext('2d'),
canvasWidth  = window.innerWidth,
canvasHeight = window.innerHeight,
gridWidth    = canvasWidth/(height+1),
gridHeight   = canvasHeight/(width+1),
dotRadius    = gridWidth * 0.4,
xoffset      = 0,
yoffset      = 0,
method       = null,
params       = null,
onConnect    = null,
onDisconnect = null,
shaders      = [
	"cpu_meter",
	"aurora",
	"timesquare",
	"unicorn",
	"fireplace",
	"notifier",
	"plasma",
	"ambilight"],
	images   = [
		"s3d.jpg",
		"twitter.jpg",
		"vrip.jpg"];
